# Generated by Django 2.1.2 on 2018-11-02 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_area', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField(max_length=1000)),
                ('Time_comment', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Landscapes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_landscapes', models.CharField(max_length=150)),
                ('Path', models.CharField(max_length=300)),
                ('Longtitude', models.CharField(max_length=200)),
                ('Latitude', models.CharField(max_length=200)),
                ('Area', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Bitdimo_API.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_images', models.IntegerField()),
                ('Number_of_comment', models.IntegerField()),
                ('Average_rating', models.FloatField()),
                ('Landscapes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bitdimo_API.Landscapes')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Province_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SubperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(choices=[('F', 'Fimale'), ('M', 'Male')], default='F', max_length=1)),
                ('Birthdate', models.DateField()),
                ('Status', models.CharField(choices=[('act', 'active'), ('uact', 'unactive')], default='uact', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Type_of_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bitdimo_API.Type_of_post'),
        ),
        migrations.AddField(
            model_name='post',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='Post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bitdimo_API.Post'),
        ),
        migrations.AddField(
            model_name='image',
            name='Type_of_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bitdimo_API.Type_of_image'),
        ),
        migrations.AddField(
            model_name='image',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluate',
            name='Post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bitdimo_API.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bitdimo_API.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='Province',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bitdimo_API.Province'),
        ),
    ]
